tên: Xây dựng README

trên:
  xô:
  quy trình làm việc_dispatch:
  lịch trình:
    - cron: '0 0 * * *'

công việc:
  xây dựng:
    chạy trên: Ubuntu-mới nhất

    chiến lược:
      ma trận:
        phiên bản nút: [12.x]

    các bước:
      - tên: Thanh toán repo
        sử dụng: hành động/thanh toán@v2
      - tên: Nút cài đặt ${{ matrix.node-version }}
        sử dụng: hành động/thiết lập-nút@v1
        với:
          phiên bản nút: ${{ matrix.node-version }}
      - tên: Cài đặt phụ thuộc
        chạy: npm ci
      - tên: Xây dựng README
        chạy: |-
          bắt đầu npm
          mèo README.md
      - tên: Cam kết với sự khác biệt
        chạy: |-
          git thêm .
          git diff
          git config --global user.email "readme-bot@stanleylim.me"
          git config --global user.name "Bot ReadMe"
          git commit -m ":sparkles: feat(README.md): README đã cập nhật" || echo "Không phát hiện thay đổi"
          đẩy git
